## How to create an empty and a full NumPy array?

In [39]:
import numpy as np

empty = np.empty((5))
print(empty)
full = np.full((2, 5), 5, dtype=np.int32)
print(full)

[1.0609979e-313 1.0609979e-313 1.0609979e-313 1.0609979e-313
 1.0609979e-313]
[[5 5 5 5 5]
 [5 5 5 5 5]]


## Create a Numpy array filled with all zeros

In [40]:
import numpy as np

zeroes_arr = np.zeros((10))
print(zeroes_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Create a Numpy array filled with all ones

In [41]:
import numpy as np

ones = np.ones((10))
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Check whether a Numpy array contains a specified row

In [42]:
import numpy as np

random_ints = np.arange(1,21).reshape((4,5))
lst = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14]]
for item in lst:
  print(item in random_ints.tolist())

True
True
False


## How to Remove rows in Numpy array that contains non-numeric values?

In [43]:
import numpy as np

arr_with_nan = np.array([[1,2,3],[4,np.nan,np.nan],[5,6,7]])
cleaned_arr = arr_with_nan[~np.isnan(arr_with_nan).any(axis=1)]
print(arr_with_nan,cleaned_arr,sep = "\n") 

[[ 1.  2.  3.]
 [ 4. nan nan]
 [ 5.  6.  7.]]
[[1. 2. 3.]
 [5. 6. 7.]]


## Remove single-dimensional entries from the shape of an array

In [44]:
import numpy as np

arr = np.arange(1,21).reshape((1,4,5))
print(arr,arr.squeeze(),sep="\n")

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


##  Find the number of occurrences of a sequence in a NumPy array

In [45]:
import numpy

arr = numpy.array([[2, 8, 9, 4], [9, 4, 9, 4], [4, 5, 9, 7], [2, 9, 4, 3]])
output = repr(arr).count("9, 4")
print(output)

4


##  Find the most frequent value in a NumPy array

In [46]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1,10])
print("Original array:",x)
print("Most frequent value in the above array:",np.bincount(x).argmax())

Original array: [ 1  2  3  4  5  1  2  1  1  1 10]
Most frequent value in the above array: 1


##  Reverse a numpy array

In [47]:
import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])
res = np.flip(ini_array)
print("final array", str(res))

final array [5 4 6 3 2 1]


## How to make a NumPy array read-only?

In [48]:
import numpy as np

a = np.zeros(11)
print("Before any change ",a,sep='\n')
a[1] = 2
print("After first change ",a,sep='\n')
a.setflags(write=False)
try:
  a[1] = 7
except Exception as e:
  print(e)

Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
assignment destination is read-only


##  Count the number of elements along a given axis

In [49]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr, np.size(arr, 0), np.size(arr, 1),sep='\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
4
5


##  How to compare two NumPy arrays?

In [50]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True
